/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calmstreetcoffeshop;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 21654
 */
public class Stats_waiter extends javax.swing.JFrame {

    Connect cnx=new Connect();
    Statement st;
    public Stats_waiter() {
        initComponents();
        affiche_drinks ();
        num.setVisible(false);
        jLabel8.setVisible(false);
        Icon();
        affiche ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        text_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        water_soda = new javax.swing.JComboBox<>();
        drinks = new javax.swing.JComboBox<>();
        hookah = new javax.swing.JComboBox<>();
        juce = new javax.swing.JComboBox<>();
        délice = new javax.swing.JComboBox<>();
        crépes = new javax.swing.JComboBox<>();
        jwajem_day = new javax.swing.JComboBox<>();
        total_water = new javax.swing.JLabel();
        total_drinks = new javax.swing.JLabel();
        total_hookah = new javax.swing.JLabel();
        total_juce = new javax.swing.JLabel();
        total_food = new javax.swing.JLabel();
        total_crepe = new javax.swing.JLabel();
        total_jwajem = new javax.swing.JLabel();
        taking_drinks = new javax.swing.JLabel();
        taking_water = new javax.swing.JLabel();
        taking_hookah = new javax.swing.JLabel();
        taking_juce = new javax.swing.JLabel();
        taking_food = new javax.swing.JLabel();
        taking_crepe = new javax.swing.JLabel();
        taking_jwajem = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        total_taking = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablestats = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ticket_stats = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Calm Street Coffeeshop");

        num.setText("jTextField3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calmstreetcoffeshop/icons8-chercher-30.png"))); // NOI18N
        jLabel2.setText("Waiter");

        jTextField2.setText("Search ");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro", "Nom", "Mot de passe", "Date", "Prénom", "Nom utilisateur", "Recette"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nom");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Date");

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jDateChooser1.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Get stats day");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("cafés");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Eau/Canette");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Hookah");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Jus");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Délices");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Crépes");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Jwajem");

        water_soda.setBackground(new java.awt.Color(255, 255, 255));
        water_soda.setForeground(new java.awt.Color(0, 0, 0));
        water_soda.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        water_soda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                water_sodaActionPerformed(evt);
            }
        });

        drinks.setBackground(new java.awt.Color(255, 255, 255));
        drinks.setForeground(new java.awt.Color(0, 0, 0));
        drinks.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        drinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinksActionPerformed(evt);
            }
        });

        hookah.setBackground(new java.awt.Color(255, 255, 255));
        hookah.setForeground(new java.awt.Color(0, 0, 0));
        hookah.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        hookah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hookahActionPerformed(evt);
            }
        });

        juce.setBackground(new java.awt.Color(255, 255, 255));
        juce.setForeground(new java.awt.Color(0, 0, 0));
        juce.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        juce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juceActionPerformed(evt);
            }
        });

        délice.setBackground(new java.awt.Color(255, 255, 255));
        délice.setForeground(new java.awt.Color(0, 0, 0));
        délice.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        délice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                déliceActionPerformed(evt);
            }
        });

        crépes.setBackground(new java.awt.Color(255, 255, 255));
        crépes.setForeground(new java.awt.Color(0, 0, 0));
        crépes.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        crépes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crépesActionPerformed(evt);
            }
        });

        jwajem_day.setBackground(new java.awt.Color(255, 255, 255));
        jwajem_day.setForeground(new java.awt.Color(0, 0, 0));
        jwajem_day.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jwajem_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jwajem_dayActionPerformed(evt);
            }
        });

        total_water.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        total_water.setForeground(new java.awt.Color(0, 0, 0));
        total_water.setText("0");

        total_drinks.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        total_drinks.setForeground(new java.awt.Color(0, 0, 0));
        total_drinks.setText("0");

        total_hookah.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        total_hookah.setForeground(new java.awt.Color(0, 0, 0));
        total_hookah.setText("0");

        total_juce.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        total_juce.setForeground(new java.awt.Color(0, 0, 0));
        total_juce.setText("0");

        total_food.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        total_food.setForeground(new java.awt.Color(0, 0, 0));
        total_food.setText("0");

        total_crepe.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        total_crepe.setForeground(new java.awt.Color(0, 0, 0));
        total_crepe.setText("0");

        total_jwajem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        total_jwajem.setForeground(new java.awt.Color(0, 0, 0));
        total_jwajem.setText("0");

        taking_drinks.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        taking_drinks.setForeground(new java.awt.Color(0, 0, 0));
        taking_drinks.setText("0");

        taking_water.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        taking_water.setForeground(new java.awt.Color(0, 0, 0));
        taking_water.setText("0");

        taking_hookah.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        taking_hookah.setForeground(new java.awt.Color(0, 0, 0));
        taking_hookah.setText("0");

        taking_juce.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        taking_juce.setForeground(new java.awt.Color(0, 0, 0));
        taking_juce.setText("0");

        taking_food.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        taking_food.setForeground(new java.awt.Color(0, 0, 0));
        taking_food.setText("0");

        taking_crepe.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        taking_crepe.setForeground(new java.awt.Color(0, 0, 0));
        taking_crepe.setText("0");

        taking_jwajem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        taking_jwajem.setForeground(new java.awt.Color(0, 0, 0));
        taking_jwajem.setText("0");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Total");

        total_taking.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        total_taking.setForeground(new java.awt.Color(0, 0, 0));

        tablestats.setBackground(new java.awt.Color(0, 0, 0));
        tablestats.setForeground(new java.awt.Color(255, 255, 255));
        tablestats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drink", "Quantity", "Total", "Date", "Time", "Waiter"
            }
        ));
        jScrollPane2.setViewportView(tablestats);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Délices");

        ticket_stats.setEditable(false);
        ticket_stats.setColumns(20);
        ticket_stats.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ticket_stats.setForeground(new java.awt.Color(0, 0, 0));
        ticket_stats.setRows(5);
        jScrollPane3.setViewportView(ticket_stats);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("print");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Reset");
        jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(text_name, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(water_soda, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(drinks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(hookah, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(juce, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(délice, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(crépes, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jwajem_day, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(total_water, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total_jwajem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total_crepe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total_drinks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total_hookah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total_juce, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total_food, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(taking_jwajem, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(taking_water, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(taking_drinks, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(taking_crepe, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(taking_food, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(taking_juce, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(taking_hookah, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(total_taking, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 43, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(total_taking, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(drinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total_drinks)
                                    .addComponent(taking_drinks))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(water_soda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total_water)
                                    .addComponent(taking_water))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(hookah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total_hookah)
                                    .addComponent(taking_hookah))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(total_juce)
                                        .addComponent(taking_juce))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(juce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(délice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total_food)
                                    .addComponent(taking_food)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(total_crepe)
                                    .addComponent(taking_crepe)
                                    .addComponent(crépes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(total_jwajem)
                                                .addComponent(taking_jwajem))
                                            .addGap(5, 5, 5)))
                                    .addComponent(jwajem_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63))
                            .addComponent(jScrollPane3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(text_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void  Icon(){     
JFrame f=new JFrame();     
Image icon = Toolkit.getDefaultToolkit().getImage("C:\\Users\\21654\\Documents\\NetBeansProjects\\CalmStreetCoffeshop\\icons\\icon.png");    
this.setIconImage(icon);    
     
} 
    void reset_taking (){
    try{
        st=(Statement) cnx.obtenircon().createStatement();
        String query ="update serveur set recette ='"+0+"' where idserveur ='"+Integer.parseInt(num.getText())+"'";
        st.execute(query);
        JOptionPane.showMessageDialog(rootPane, "Updated");
    }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
    }
    void getvaluesFromTable(){
    DefaultTableModel table = (DefaultTableModel) tablestats.getModel();
        int rows = table.getRowCount();
        int cols = table.getColumnCount();
        Object[][] tableData = new Object[rows][cols];
        ticket_stats.append("Recette de :"+text_name.getText()+" le :"+jLabel8.getText()+"\n");
        for (int i = 0; i < rows; i++) {
            String drink = table.getValueAt(i, 0).toString();
            String qte = table.getValueAt(i, 1).toString();
            String total = table.getValueAt(i, 2).toString();
            
            if (drink.length() < 13) {
                ticket_stats.setText(ticket_stats.getText()+ qte + "\t" + drink + "\t \t" + total + "\t" + "\n");
            } else {
                ticket_stats.setText(ticket_stats.getText()+ qte + "\t" + drink + "\t" + total + "\t" + "\n");
            }
}
        ticket_stats.append("Total = "+total_taking.getText());
        //print 
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        PageFormat pageFormat = printerJob.defaultPage();
        Paper paper = new Paper();
        paper.setSize(110, 25);
        pageFormat.setPaper(paper);
        pageFormat.setOrientation(PageFormat.PORTRAIT);
        printerJob.setPrintable(ticket_stats.getPrintable(null, null), pageFormat);
        try {
            printerJob.print();
        } catch (PrinterException ex) {
            java.util.logging.Logger.getLogger(TabelsAndOrders.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    void affiche_drinks (){
     try{
             st=(Statement) cnx.obtenircon().createStatement();
            ResultSet rs=st.executeQuery("select name, category from drink");
            while(rs.next()){
                String name = rs.getString("name");
                String category = rs.getString("category");System.out.print(category);
                switch(category){
                    case "Hookah":
                        hookah.addItem(name);
                    break;
                    case "Coffee and tea":
                        drinks.addItem(name);
                        break;
                    case "Soda":
                        water_soda.addItem(name);
                    break;
                    case "Water":
                        water_soda.addItem(name);
                        break;
                    case "Délice":
                        délice.addItem(name);
                        break;
                    case "jus":
                        juce.addItem(name);
                        break;
                    case "Crépes":
                        crépes.addItem(name);
                        break;
                    case "Jwajem":
                        jwajem_day.addItem(name);
                        break;
                        
                }  
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane,e);
        }
}
    void get_qte_drinks(){
      try{ 
        SimpleDateFormat tdate = new SimpleDateFormat("dd/MM/yyyy");
        String addDate = tdate.format(jDateChooser1.getDate()); System.out.print(addDate);
        jLabel8.setText(addDate);
        java.util.Date date;
        date = tdate.parse(addDate);
        java.sql.Date sqldate = new java.sql.Date(date.getTime());System.out.println("sql date drinks "+sqldate);
          String query = "select SUM(qte) as total, SUM(total) as totaldrinks from stats where drink ='"+drinks.getSelectedItem()+"'  and date='"+sqldate+"' and name_waiter='"+text_name.getText()+"'";
          int tot;
          double totaldrinks;
          st=(Statement) cnx.obtenircon().createStatement();
          ResultSet rs=st.executeQuery(query);
          while(rs.next()){
              tot=rs.getInt("total");System.out.print(tot);
              totaldrinks = rs.getDouble("totaldrinks");
              total_drinks.setText(""+tot);
              taking_drinks.setText(""+totaldrinks);
          }
      }catch(Exception e){
          //JOptionPane.showMessageDialog(rootPane, e);
      }
  }
    ///////////water ///////////
  void get_qte_water(){
      try{
        SimpleDateFormat tdate = new SimpleDateFormat("dd/MM/yyyy");
        String addDate = tdate.format(jDateChooser1.getDate()); System.out.print(addDate);
        jLabel8.setText(addDate);
        java.util.Date date;
        date = tdate.parse(addDate);
        java.sql.Date sqldate = new java.sql.Date(date.getTime());System.out.println("sql date drinks "+sqldate);
          String query = "select SUM(qte) as total, SUM(total) as totalwater from stats where drink ='"+water_soda.getSelectedItem()+"' and date='"+sqldate+"' and name_waiter='"+text_name.getText()+"'";
          int tot;
          double tottaking;
          st=(Statement) cnx.obtenircon().createStatement();
          ResultSet rs=st.executeQuery(query);
          while(rs.next()){
              tot=rs.getInt("total");System.out.print(tot);
              tottaking = rs.getDouble("totalwater");
              total_water.setText(""+tot);
              taking_water.setText(""+tottaking);
          }
      }catch(Exception e){
          //JOptionPane.showMessageDialog(rootPane, e);
      }
  }
  void get_qte_crepe(){
      try{
        SimpleDateFormat tdate = new SimpleDateFormat("dd/MM/yyyy");
        String addDate = tdate.format(jDateChooser1.getDate()); System.out.print(addDate);
        jLabel8.setText(addDate);
        java.util.Date date;
        date = tdate.parse(addDate);
        java.sql.Date sqldate = new java.sql.Date(date.getTime());System.out.println("sql date drinks "+sqldate);
          String query = "select SUM(qte) as qtecrepe, SUM(total) as totalcreps from stats where drink ='"+crépes.getSelectedItem()+"' and name_waiter='"+text_name.getText()+"'and date='"+sqldate+"'";
          int tot;
          double tottaking;
          st=(Statement) cnx.obtenircon().createStatement();
          ResultSet rs=st.executeQuery(query);
          while(rs.next()){
              tot=rs.getInt("qtecrepe");System.out.print(tot);
              tottaking = rs.getDouble("totalcreps");
              total_crepe.setText(""+tot);
              taking_crepe.setText(""+tottaking);
          }
      }catch(Exception e){
          //JOptionPane.showMessageDialog(rootPane, e);
      }
  }
  void get_qte_jwajem(){
      try{
        SimpleDateFormat tdate = new SimpleDateFormat("dd/MM/yyyy");
        String addDate = tdate.format(jDateChooser1.getDate()); System.out.print(addDate);
        jLabel8.setText(addDate);
        java.util.Date date;
        date = tdate.parse(addDate);
        java.sql.Date sqldate = new java.sql.Date(date.getTime());System.out.println("sql date drinks "+sqldate);
          String query = "select SUM(qte) as qtejwajem, SUM(total) as totaljwajem from stats where drink ='"+jwajem_day.getSelectedItem()+"' and name_waiter='"+text_name.getText()+"' and date='"+sqldate+"'";
          int tot;
          double tottaking;
          st=(Statement) cnx.obtenircon().createStatement();
          ResultSet rs=st.executeQuery(query);
          while(rs.next()){
              tot=rs.getInt("qtejwajem");System.out.print(tot);
              tottaking = rs.getDouble("totaljwajem");
              total_jwajem.setText(""+tot);
              taking_jwajem.setText(""+tottaking);
          }
      }catch(Exception e){
          //JOptionPane.showMessageDialog(rootPane, e);
      }
  }
  void get_qte_juce(){
      try{
        SimpleDateFormat tdate = new SimpleDateFormat("dd/MM/yyyy");
        String addDate = tdate.format(jDateChooser1.getDate()); System.out.print(addDate);
        jLabel8.setText(addDate);
        java.util.Date date;
        date = tdate.parse(addDate);
        java.sql.Date sqldate = new java.sql.Date(date.getTime());System.out.println("sql date drinks "+sqldate);
          String query = "select SUM(qte) as total, SUM(total) as totaljuce from stats where drink ='"+juce.getSelectedItem()+"' and name_waiter='"+text_name.getText()+"' and date='"+sqldate+"'";
          int tot;
          double tottaking;
          st=(Statement) cnx.obtenircon().createStatement();
          ResultSet rs=st.executeQuery(query);
          while(rs.next()){
              tot=rs.getInt("total");System.out.print(tot);
              tottaking = rs.getDouble("totaljuce");
              total_juce.setText(""+tot);
              taking_juce.setText(""+tottaking);
          }
      }catch(Exception e){
          //JOptionPane.showMessageDialog(rootPane, e);
      }
  }
  void get_qte_hookah(){
      try{
        SimpleDateFormat tdate = new SimpleDateFormat("dd/MM/yyyy");
        String addDate = tdate.format(jDateChooser1.getDate()); System.out.print(addDate);
        jLabel8.setText(addDate);
        java.util.Date date;
        date = tdate.parse(addDate);
        java.sql.Date sqldate = new java.sql.Date(date.getTime());System.out.println("sql date drinks "+sqldate);
          String query = "select SUM(qte) as total, SUM(total) as totalhookah from stats where drink ='"+hookah.getSelectedItem()+"' and name_waiter='"+text_name.getText()+"' and date='"+sqldate+"'";
          int tot;
          double tottaking;
          st=(Statement) cnx.obtenircon().createStatement();
          ResultSet rs=st.executeQuery(query);
          while(rs.next()){
              tot=rs.getInt("total");System.out.print(tot);
              tottaking = rs.getDouble("totalhookah");
              total_hookah.setText(""+tot);
              taking_hookah.setText(""+tottaking);
          }
      }catch(Exception e){
          //JOptionPane.showMessageDialog(rootPane, e);
      }
  }
  void get_qte_food(){
      try{
        SimpleDateFormat tdate = new SimpleDateFormat("dd/MM/yyyy");
        String addDate = tdate.format(jDateChooser1.getDate()); System.out.print(addDate);
        jLabel8.setText(addDate);
        java.util.Date date;
        date = tdate.parse(addDate);
        java.sql.Date sqldate = new java.sql.Date(date.getTime());System.out.println("sql date drinks "+sqldate);
          String query = "select SUM(qte) as totalqte, SUM(total) as totaltaking  from stats where drink ='"+délice.getSelectedItem()+"' and name_waiter='"+text_name.getText()+"' and date='"+sqldate+"'";
          int tot;
          double tottaking;
          st=(Statement) cnx.obtenircon().createStatement();
          ResultSet rs=st.executeQuery(query);
          while(rs.next()){
              tot=rs.getInt("totalqte");System.out.println(tot);
              tottaking=rs.getInt("totaltaking");System.out.println(tottaking);
              total_food.setText(""+tot);
              taking_food.setText(""+tottaking);
          }
      }catch(Exception e){
          //JOptionPane.showMessageDialog(rootPane, e);
      }
  }
  void get_stats (){
      try{
        String date_txt = jLabel8.getText();System.out.println(date_txt);
        SimpleDateFormat sdf1 = new SimpleDateFormat("dd/MM/yyyy");
        java.util.Date date;
        date = sdf1.parse(date_txt);
        java.sql.Date sqldate = new java.sql.Date(date.getTime());System.out.println("sql date "+sqldate);
          DefaultTableModel table=(DefaultTableModel) tablestats.getModel();
          String query = "select drink, qte, total, date, time, name_waiter from stats where date = '"+sqldate+"' and name_waiter='"+text_name.getText()+"'";
          st=cnx.obtenircon().createStatement();
          ResultSet rs=st.executeQuery(query);
            while(rs.next()){
                table.addRow(new Object[] {rs.getString("drink"),rs.getString("qte"),rs.getString("total"),rs.getString("date"),rs.getString("time"),rs.getString("name_waiter")});
            }
      }catch(Exception e){
          JOptionPane.showMessageDialog(rootPane, e);
      }
      
  }
  void get_total_day(){
      try{
          String date_txt = jLabel8.getText();System.out.println(date_txt);
          SimpleDateFormat sdf1 = new SimpleDateFormat("dd/MM/yyyy");
        java.util.Date date;
        date = sdf1.parse(date_txt);
        java.sql.Date sqldate = new java.sql.Date(date.getTime());System.out.println("sql date "+sqldate);
          double tot;
          String query = "select SUM(total) as tot from stats where date = '"+sqldate+"' and name_waiter='"+text_name.getText()+"'";
          st=cnx.obtenircon().createStatement();
          ResultSet rs=st.executeQuery(query);
          while (rs.next()){
              tot = rs.getDouble("tot");
              total_taking.setText(""+tot);
          }
      }catch(Exception e){
          JOptionPane.showMessageDialog(rootPane, e);
      }
  }
  boolean check_date (){
        boolean test = false;
        //String date_txt = jLabel8.getText();System.out.println(date_txt);
        
        SimpleDateFormat sdf1 = new SimpleDateFormat("dd/MM/yyyy");
        java.util.Date date;
        date = jDateChooser1.getDate();
        
        if (date==null){JOptionPane.showMessageDialog(rootPane, "Select a date ");}
        java.sql.Date sqldate = new java.sql.Date(date.getTime());
        System.out.println("sql date "+sqldate);
        if (sqldate==null){
            JOptionPane.showMessageDialog(rootPane, "Select a date ");
            test = false;
        }else{
            test = true;
        }
        return test;
    }
    void affiche (){
    DefaultTableModel table=(DefaultTableModel) jTable1.getModel();
        try{
            st=cnx.obtenircon().createStatement();
            ResultSet rs=st.executeQuery("select * from serveur");
            while(rs.next()){
                table.addRow(new Object[] {rs.getString("idserveur"),rs.getString("nom"),rs.getString("password"),rs.getString("date"),rs.getString("last_name"),rs.getString("user_name"),rs.getString("recette")});
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane,e);
        }
}
    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        DefaultTableModel tab =(DefaultTableModel)jTable1.getModel();
        jTextField2.setText("Search");
        tab.setRowCount(0);
        affiche();
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        DefaultTableModel table =(DefaultTableModel)jTable1.getModel();
        table.setRowCount(0);
        
            char c=evt.getKeyChar();System.out.println(c);
            try{
                st=cnx.obtenircon().createStatement();
                ResultSet rs=st.executeQuery("select *  from serveur where nom like '%"+c+"%'");
                while(rs.next()){
                    table.addRow(new Object[] {rs.getString("idserveur"),rs.getString("nom"),rs.getString("password"),rs.getString("date"),rs.getString("last_name"),rs.getString("user_name")});}
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(rootPane, e);
            }
        
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        try{
            DefaultTableModel table=(DefaultTableModel) jTable1.getModel();
            st = (Statement) cnx.obtenircon().createStatement();
            int row = jTable1.getSelectedRow();System.out.println("Row"+row);
            if (row<0){
                System.out.println("rows <1");
                try{
                    char c = jTextField2.getText().charAt(1);
                    st=cnx.obtenircon().createStatement();
                    table.setRowCount(0);
                    ResultSet rs=st.executeQuery("select idserveur ,nom, password, date, last_name, user_name, recette from serveur where nom like '%"+c+"%'");
                    while(rs.next()){
                        table.addRow(new Object[] {rs.getString("idserveur"),rs.getString("nom"),rs.getString("password"),rs.getString("date"),rs.getString("last_name"),rs.getString("user_name"),rs.getString("recette")});}
                }
                catch(SQLException e){
                    JOptionPane.showMessageDialog(rootPane, e);
                }
            }else{
                try{

                    String tab=(jTable1.getModel().getValueAt(row,0).toString());System.out.println("colomn"+tab);
                    ResultSet rs =st.executeQuery("select idserveur ,nom, password, date, last_name, user_name from serveur where idserveur='"+tab+"'");
                    if(rs.next()){
                        String add=rs.getString("idserveur");
                        num.setText(add);
                        String add1=rs.getString("nom");
                        text_name.setText(add1);
                        
                    }
                }catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane, e);
                }
            }

        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        /*
        try{
            st = (Statement) cnx.obtenircon().createStatement();
            int row=jTable1.getSelectedRow();
            String tab = (jTable1.getValueAt(row, 0).toString());
            ResultSet rs =st.executeQuery("select idserveur ,nom, password, date, last_name, user_name from serveur where idserveur='"+tab+"'");
            if(rs.next()){
                String add=rs.getString("idserveur");
                num.setText(add);
                String add5=rs.getString("user_name");
                user_name.setText(add5);
                String add6=rs.getString("last_name");
                last_name.setText(add6);
                String add1=rs.getString("nom");
                text_name.setText(add1);
                String add2=rs.getString("password");
                jPasswordField2.setText(add2);
                String add3=rs.getString("password");
                jPasswordField1.setText(add3);
                String add4=rs.getString("date");
                jDateChooser1.setDate(Date.valueOf(add4));
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }*/
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean test = check_date();
        if (test=false){
            JOptionPane.showMessageDialog(rootPane, "Select a date ");
        }else{
            DefaultTableModel table=(DefaultTableModel) jTable1.getModel();
            SimpleDateFormat tdate = new SimpleDateFormat("dd/MM/yyyy");
            String addDate = tdate.format(jDateChooser1.getDate()); System.out.print(addDate);
            jLabel8.setText(addDate);
            get_qte_drinks();get_qte_water();get_qte_hookah();get_qte_food();get_qte_juce();get_qte_crepe();
            //table.setRowCount(0);
            get_stats();
            get_total_day();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void water_sodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_water_sodaActionPerformed
        get_qte_water();
    }//GEN-LAST:event_water_sodaActionPerformed

    private void drinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinksActionPerformed
        get_qte_drinks();
    }//GEN-LAST:event_drinksActionPerformed

    private void hookahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hookahActionPerformed
        get_qte_hookah();
    }//GEN-LAST:event_hookahActionPerformed

    private void juceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juceActionPerformed
        get_qte_juce();
    }//GEN-LAST:event_juceActionPerformed

    private void déliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_déliceActionPerformed
        get_qte_food();
    }//GEN-LAST:event_déliceActionPerformed

    private void crépesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crépesActionPerformed
        get_qte_crepe();
    }//GEN-LAST:event_crépesActionPerformed

    private void jwajem_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jwajem_dayActionPerformed
        get_qte_jwajem();
    }//GEN-LAST:event_jwajem_dayActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        getvaluesFromTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel table=(DefaultTableModel) jTable1.getModel();
        reset_taking ();
        table.setRowCount(0);
        affiche ();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stats_waiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stats_waiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stats_waiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stats_waiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stats_waiter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> crépes;
    private javax.swing.JComboBox<String> drinks;
    private javax.swing.JComboBox<String> délice;
    private javax.swing.JComboBox<String> hookah;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> juce;
    private javax.swing.JComboBox<String> jwajem_day;
    private javax.swing.JTextField num;
    private javax.swing.JTable tablestats;
    private javax.swing.JLabel taking_crepe;
    private javax.swing.JLabel taking_drinks;
    private javax.swing.JLabel taking_food;
    private javax.swing.JLabel taking_hookah;
    private javax.swing.JLabel taking_juce;
    private javax.swing.JLabel taking_jwajem;
    private javax.swing.JLabel taking_water;
    private javax.swing.JTextField text_name;
    private javax.swing.JTextArea ticket_stats;
    private javax.swing.JLabel total_crepe;
    private javax.swing.JLabel total_drinks;
    private javax.swing.JLabel total_food;
    private javax.swing.JLabel total_hookah;
    private javax.swing.JLabel total_juce;
    private javax.swing.JLabel total_jwajem;
    private javax.swing.JLabel total_taking;
    private javax.swing.JLabel total_water;
    private javax.swing.JComboBox<String> water_soda;
    // End of variables declaration//GEN-END:variables
}
